version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
